name: CI

on: push

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Berlin
      - run: npm run test:unit:coverage
        env:
          FORCE_COLOR: 1
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/coverage/clover.xml
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Check source code
        run: |
          npm run lint
          npm run copy:paste:detection
      - name: Compile source code
        run: npm run compile
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Berlin
      - name: Run unit tests
        run: npm run test:unit
        env:
          FORCE_COLOR: 1
      - name: Run integration tests
        run: npm run test:integration
        env:
          FORCE_COLOR: 1
      - name: Run mutation tests
        run: npm run test:unit:mutation
