name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Check source code
        run: |
          npm run lint
          npm run copy:paste:detection
      - name: Compile source code
        run: npm run compile
      - name: Run unit tests
        run: npm run test:unit:coverage
        env:
          FORCE_COLOR: 1
      - name: Run integration tests
        run: npm run test:integration
        env:
          FORCE_COLOR: 1
